FROM ubuntu:16.04

# Labels
LABEL maintainer "ecali301@gmail.com"

# ENVIRONMENT VARIABLES
ENV PROJECT_PATH=/var/www \
    DEBIAN_FRONTEND=noninteractive \
    APACHE_RUN_USER=www-data \
    APACHE_RUN_GROUP=www-data \
    APACHE_LOG_DIR=/var/log/apache2 \
    APACHE_LOCK_DIR=/var/lock/apache2 \
    PHP_INI=/etc/php/7.0/apache2/php.ini \
    TERM=xterm

# UPDATE, UPGRADE AND CURL INSTALLATION
RUN apt-get update -q && apt-get upgrade -yqq && apt-get install -yqq curl locales

# UPDATE, UPGRADE AND PHP-MYSQL INSTALLATION
RUN apt-get update -q && apt-get install -yqq --force-yes \
    php-mysql

# LOCALE GENERATOR
RUN locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

ENV COMPOSER_ALLOW_SUPERUSER 1

# UTILITIES, APACHE, PHP, AND SUPPLEMENTARY PROGRAMS
RUN apt-get update -q && apt-get install -yqq --force-yes \
    git \
    wget \
    zip \
    apache2 \
    libapache2-mod-php \
    php \
    php-bcmath \
    php-curl \
    php-dom \
    php-mbstring \
    php-intl \
    nano

# APACHE MODS
RUN a2enmod rewrite expires headers

# APACHE2 CONF
RUN echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf
RUN a2enconf fqdn

RUN curl --silent --show-error https://getcomposer.org/installer | php

# PHP.INI CONFIGS
RUN sed -i "s/short_open_tag = .*/short_open_tag = On/" $PHP_INI && \
    sed -i "s/memory_limit = .*/memory_limit = 256M/" $PHP_INI && \
    sed -i "s/display_errors = .*/display_errors = Off/" $PHP_INI && \
    sed -i "s/display_startup_errors = .*/display_startup_errors = Off/" $PHP_INI && \
    sed -i "s/post_max_size = .*/post_max_size = 64M/" $PHP_INI && \
    sed -i "s/upload_max_filesize = .*/upload_max_filesize = 32M/" $PHP_INI && \
    sed -i "s/max_file_uploads = .*/max_file_uploads = 10/" $PHP_INI && \
    sed -i "s/error_reporting = .*/error_reporting = E_ALL \& ~E_DEPRECATED \& ~E_STRICT/" $PHP_INI

# CLEANUP
RUN apt-get purge -yq \
    patch \
    software-properties-common \
    wget && \
    apt-get autoremove -yqq && \
    apt-get clean

# VIRTUALHOST
COPY config/apache-virtualhost.conf /etc/apache2/sites-available/000-default.conf

# PORT TO EXPOSE
EXPOSE 80 443

# WORKDIR
WORKDIR $PROJECT_PATH

# COMPOSER
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# START APACHE
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]