version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  db:
    image: mysql:5.6.26
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=phpmyadmin.slim.dev
  web:
    build:
      context: .
      dockerfile: Dockerfile_development
    volumes:
      - ".:/var/www/"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=*.slim.dev
